name       : lsof
version    : 4.93.2
release    : 3
source     :
    - https://github.com/lsof-org/lsof/archive/4.93.2.tar.gz : 3df912bd966fc24dc73ddea3e36a61d79270b21b085936a4caabca56e5b486a2
homepage   : https://github.com/lsof-org/lsof
license    : BSD-4-Clause-UC
component  : system.utils
summary    : lsof (for LiSt Open Files) displays information about files open to Unix processes
description: |
    lsof (for LiSt Open Files) displays information about files open to Unix processes
setup      : |
    sed -i 's|\.so \./version|.ds VN %version%|' Lsof.8
    LSOF_CC="${CC}" LSOF_CFGF="${CFLAGS}" LSOF_CFGL="${LDFLAGS}" ./Configure -n linux
build      : |
    %make
install    : |
    install -Dm00755 lsof $installdir/usr/bin/lsof
    install -Dm00644 Lsof.8 $installdir/usr/share/man/man8/lsof.8
