name       : lsof
version    : 4.94.0
release    : 4
source     :
    - https://github.com/lsof-org/lsof/releases/download/4.94.0/lsof_4.94.0.linux.tar.bz2 : c41709c2543ecf9de1e950795790a9786a2f225e51c3cc53d6a9a256f872472b
homepage   : https://github.com/lsof-org/lsof
license    : BSD-4-Clause-UC
component  : system.utils
summary    : lsof (for LiSt Open Files) displays information about files open to Unix processes
description: |
    lsof (for LiSt Open Files) displays information about files open to Unix processes
setup      : |
    sed -i 's|\.so \./version|.ds VN %version%|' lsof.8
    LSOF_CC="${CC}" LSOF_CFGF="${CFLAGS}" LSOF_CFGL="${LDFLAGS}" ./Configure -n linux
build      : |
    %make
install    : |
    install -Dm00755 lsof $installdir/usr/bin/lsof
    install -Dm00644 lsof.8 $installdir/usr/share/man/man8/lsof.8
