name       : lsof
version    : 4.91
release    : 2
source     :
    - ftp://ftp.fu-berlin.de/pub/unix/tools/lsof/lsof_4.91.tar.gz : 3ca57887470fdf223a8e8aae4559cd3a26787bea93b94336c90ee8062e29e352
license    : BSD-4-Clause-UC
component  : system.utils
summary    : lsof (for LiSt Open Files) displays information about files open to Unix processes
description: |
    lsof (for LiSt Open Files) displays information about files open to Unix processes
setup      : |
    tar xf lsof_${version}_src.tar
    cd lsof_${version}_src
    ./Configure -n linux
build      : |
    %make -C lsof_${version}_src
install    : |
    cd lsof_${version}_src
    install -Dm00755 lsof $installdir/usr/bin/lsof
    install -Dm00644 lsof.8 $installdir/usr/share/man/man8/lsof.8
