name       : lsof
version    : 4.89
release    : 1
source     :
    - ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_4.89.tar.bz2 : 81ac2fc5fdc944793baf41a14002b6deb5a29096b387744e28f8c30a360a3718
license    : BSD-4-Clause-UC
component  : system.utils
summary    : lsof (for LiSt Open Files) displays information about files open to Unix processes
description: |
    lsof (for LiSt Open Files) displays information about files open to Unix processes
setup      : |
    tar xf lsof_4.89_src.tar
    cd lsof_4.89_src
    ./Configure -n linux
build      : |
    cd lsof_4.89_src
    %make
install    : |
    cd lsof_4.89_src
    install -Dm755 lsof $installdir/usr/bin/lsof
    install -Dm644 lsof.8 $installdir/usr/share/man/man8/lsof.8
